# Generated by Django 3.0.5 on 2020-04-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_auto_20200421_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='seller',
        ),
    ]
