# Generated by Django 3.0.5 on 2020-04-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_auto_20200421_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='product',
            new_name='product_bought',
        ),
    ]
