# Generated by Django 3.0.5 on 2020-04-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_auto_20200421_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='product_name',
        ),
    ]
