# Generated by Django 3.0.5 on 2020-04-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0005_auto_20200421_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_picture',
        ),
    ]
