# Generated by Django 3.0.5 on 2020-04-21 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_remove_product_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 5, 27, 28, 799836, tzinfo=utc), verbose_name='date published'),
        ),
    ]
