# Generated by Django 3.0.5 on 2020-04-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0009_auto_20200421_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Country',
            field=models.CharField(blank=True, default='Canada', max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='Zipcode',
            field=models.CharField(default='H1H 1H1', max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_one',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_two',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
