# Generated by Django 3.0.5 on 2020-04-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0010_auto_20200422_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
