# Generated by Django 2.0.7 on 2020-04-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0011_auto_20200422_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, upload_to="{% static '/image/' %}"),
        ),
    ]
