# Generated by Django 3.0.5 on 2020-04-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0011_auto_20200422_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
