# Generated by Django 3.0.5 on 2020-04-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0012_auto_20200422_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product_bought',
        ),
        migrations.AddField(
            model_name='product',
            name='changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='description',
            field=models.CharField(default='No Description', max_length=50),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_name',
            field=models.CharField(default='Name Missing', max_length=50),
        ),
    ]
