# Generated by Django 2.0.7 on 2020-04-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0013_product_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
