# Generated by Django 2.0.7 on 2020-04-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0014_auto_20200422_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, upload_to='item_pics/'),
        ),
    ]
