# Generated by Django 2.0.7 on 2020-04-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0015_auto_20200422_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
