# Generated by Django 3.0.5 on 2020-04-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0016_auto_20200422_2155'),
        ('Market', '0014_purchase_product'),
    ]

    operations = [
    ]
